<?php

namespace ParkingMapBundle\Repository;

use ParkingMapBundle\Entity\Slots as Slots;

/**
 * SlotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSlotsNb() {
        $qb = $this->createQueryBuilder('sl');

        $qb->select('COUNT(sl)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getFreeSlotsNb() {
        $qb = $this->createQueryBuilder('sl');

        $qb->select('COUNT(sl)')
            ->where("sl.currentState = 1");


        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getFreeSlots() {
        $qb = $this->createQueryBuilder('sl')
            ->where("sl.currentState = 1");

        return $qb->getQuery()->getResult();
    }
}
