<?php

namespace ParkingMapBundle\Repository;

use ParkingMapBundle\Entity\Slots;

/**
 * SlotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllStatesByHoursSpan($hourStart, $hourEnd) {

        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select(array('sl', 'st'))
            ->from('ParkingMapBundle\Entity\Slots', 'sl')
            ->join('sl.states', 'st')
            ->where("st.date <= :hourStart AND st.date >= :hourEnd")
            ->setParameter('hourStart', $hourStart)
            ->setParameter('hourEnd', $hourEnd);

        return $qb->getQuery()->getResult();


    }
}
