<?php

namespace ParkingMapBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{

}
