# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    pkm.data_handler:
       class: ParkingMapBundle\Service\DataHandler
       arguments: ['@doctrine.orm.entity_manager', '@pkm.time_handler']

    pkm.time_handler:
        class: ParkingMapBundle\Service\TimeHandler
